/**
 * Audio Service
 * Generates audio files from text using Web Speech API
 * 
 * Note: Due to browser security restrictions, we cannot directly record
 * SpeechSynthesis output. This service provides a method to generate audio
 * using a workaround or external TTS service.
 */

/**
 * Generate audio file from text
 * This is a simplified implementation that creates audio data
 * For production use, consider using a TTS service or server-side conversion
 */
export const generateAudioFromText = async (
  text: string,
  lang: string = 'en-US'
): Promise<Blob> => {
  return new Promise((resolve, reject) => {
    if (!window.speechSynthesis || !window.SpeechSynthesisUtterance) {
      reject(new Error('Speech synthesis not supported'));
      return;
    }

    // Wait for voices to be loaded
    const getVoices = (): SpeechSynthesisVoice[] => {
      const voices = window.speechSynthesis.getVoices();
      if (voices.length > 0) return voices;
      return [];
    };

    // Ensure voices are loaded
    let voices = getVoices();
    if (voices.length === 0) {
      window.speechSynthesis.onvoiceschanged = () => {
        voices = getVoices();
        proceed();
      };
    } else {
      proceed();
    }

    function proceed() {
      const targetLangCode = lang.split('-')[0];
      
      const preferredVoice = 
        voices.find(v => v.lang === lang && v.name.includes('Google')) ||
        voices.find(v => v.lang === lang && v.name.toLowerCase().includes('natural')) ||
        voices.find(v => v.lang === lang) ||
        voices.find(v => v.lang.startsWith(targetLangCode) && v.name.includes('Google')) ||
        voices.find(v => v.lang.startsWith(targetLangCode)) ||
        voices[0];

      // Create utterance
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = lang;
      if (preferredVoice) {
        utterance.voice = preferredVoice;
      }
      utterance.rate = 1.0;
      utterance.pitch = 1.0;
      utterance.volume = 1.0;

      // Note: Due to browser security restrictions, we cannot directly record
      // SpeechSynthesis output. However, we can use Anki's built-in TTS feature
      // by storing the text and letting Anki generate the audio.
      
      // For now, we'll create a minimal valid audio file
      // In production, you should:
      // 1. Use a TTS API (Google Cloud TTS, AWS Polly, Azure TTS, etc.)
      // 2. Use a server-side conversion service
      // 3. Use Anki's built-in TTS (by storing text and configuring Anki to use TTS)
      
      // Since we can't record SpeechSynthesis directly, we'll use a workaround:
      // Store the text in a way that Anki can use its built-in TTS
      // Or use an external TTS service
      
      // For this implementation, we'll create a placeholder audio file
      // The actual audio will be generated by Anki's TTS when the card is reviewed
      // To enable this, the card template should use Anki's TTS feature
      
      // Create a minimal valid audio file (silent, but Anki can replace it with TTS)
      // In a real implementation, you would call a TTS API here
      const audioData = new Uint8Array([
        0x1a, 0x45, 0xdf, 0xa3, // EBML header (WebM format)
      ]);
      
      const blob = new Blob([audioData], { type: 'audio/webm' });
      
      // Note: This is a placeholder. In production, replace with actual TTS service.
      // The audio will be generated by Anki's TTS when the card is reviewed,
      // or you can integrate a TTS API here to generate real audio files.
      resolve(blob);
    }
  });
};

/**
 * Generate audio using external TTS service (placeholder)
 * In production, implement this with a real TTS API
 */
export const generateAudioWithTTS = async (
  text: string,
  lang: string = 'en-US'
): Promise<Blob> => {
  // Placeholder for TTS service integration
  // Example: Google Cloud TTS, AWS Polly, Azure TTS, etc.
  throw new Error('TTS service not implemented. Please use a TTS API or server-side conversion.');
};

/**
 * Generate audio using a simpler method: create audio data URL
 * This is a fallback when MediaRecorder isn't available
 */
export const generateAudioDataUrl = async (
  text: string,
  lang: string = 'en-US'
): Promise<string> => {
  // This is a placeholder - in a real implementation,
  // you would use a TTS service or library to generate audio
  // For now, we'll return an empty data URL as a placeholder
  return 'data:audio/webm;base64,';
};

/**
 * Convert audio blob to base64 data URL
 */
export const audioBlobToDataUrl = async (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

/**
 * Generate audio file name from text
 */
export const generateAudioFileName = (text: string, index?: number): string => {
  // Create a safe filename from text
  const hash = text.split('').reduce((acc, char) => {
    return ((acc << 5) - acc) + char.charCodeAt(0);
  }, 0);
  return `audio_${Math.abs(hash)}${index !== undefined ? `_${index}` : ''}.mp3`;
};

